apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-service-app
  labels:
    app: document-service-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: document-service-app
  template:
    metadata:
      labels:
        app: document-service-app
    spec:
      containers:
        - name: document-service-app
          image: <IMAGE_PLACEHOLDER>
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq-service"
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: "guest"
            - name: SPRING_RABBITMQ_PASSWORD
              value: "guest"
          readinessProbe:
            httpGet:
              path: /api/v1/actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/v1/actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10