apiVersion: v1
kind: Service
metadata:
  name: document-service-app-service
spec:
  selector:
    app: document-service-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
